###
POST http://localhost:3000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "name":"Santiago",
  "lastname":"OcaGalvismpo",
  "age": "20",
  "address":{
    "city":"Manizales",
    "code_zip":"170001"
  }
}

###
GET http://localhost:3000/api/v1/people HTTP/1.1

###
GET http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1

###
PUT http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1
Content-Type: application/json

{
  "name":"Santiago 2",
  "lastname":"OcaGalvis 2mpo",
  "age": "20",
  "address":{
    "city":"Bogota",
    "code_zip":"110001"
  }
}

###
DELETE http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments/5 HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments/filter/code HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments/filter/search?departamentId=5 HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments/filter/name?municipalityName=Cajibío HTTP/1.1

###
GET http://localhost:3000/api/v1/departaments/filter/letter HTTP/1.1