###
POST http://localhost:3000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "name":"Santiago",
  "lastname":"Galvis",
  "age": "20",
  "address":{
    "city":"Manizales",
    "code_zip":"170001"
  }
}

###
GET http://localhost:3000/api/v1/people HTTP/1.1

###
GET http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1

###
PUT http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1
Content-Type: application/json

{
  "name":"Santiago 2",
  "lastname":"Galvis 2",
  "age": "20",
  "address":{
    "city":"Bogota",
    "code_zip":"110001"
  }
}

###
DELETE http://localhost:3000/api/v1/people/624e3ae7a3fbd554900ead2d HTTP/1.1


//----------------------------Super Hero-------------------------------------
###
POST http://localhost:3000/api/v1/superheros/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"Heroe 1",
  "realname":"Hero 1"
}

###
GET http://localhost:3000/api/v1/superheros HTTP/1.1
###
GET http://localhost:3000/api/v1/superheros/625a238d8c78baaf1fa73f6c HTTP/1.1
###
PUT http://localhost:3000/api/v1/superheros/625a238d8c78baaf1fa73f6c HTTP/1.1
Content-Type: application/json

{
  "superhero":"Heroe 2",
  "realname":"Hero 2"
}

###
DELETE http://localhost:3000/api/v1/superheros/625a238d8c78baaf1fa73f6c HTTP/1.1